// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYauOq9JpveEqggILyQW_izKeNJVJqqF4',
    appId: '1:578618171508:web:5c815886aecd20dcebf121',
    messagingSenderId: '578618171508',
    projectId: 'chat-app-84de6',
    authDomain: 'chat-app-84de6.firebaseapp.com',
    storageBucket: 'chat-app-84de6.firebasestorage.app',
    measurementId: 'G-G8VP3ZEPFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoTE4leSaXW-eZzGfjRCG_kPQ0dw_YkV0',
    appId: '1:578618171508:android:c9ea8ea8f8d9d3b0ebf121',
    messagingSenderId: '578618171508',
    projectId: 'chat-app-84de6',
    storageBucket: 'chat-app-84de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtX1y09JBO4iIV8F7r2riHARU4Murj_cQ',
    appId: '1:578618171508:ios:2d48cc8187de144bebf121',
    messagingSenderId: '578618171508',
    projectId: 'chat-app-84de6',
    storageBucket: 'chat-app-84de6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtX1y09JBO4iIV8F7r2riHARU4Murj_cQ',
    appId: '1:578618171508:ios:2d48cc8187de144bebf121',
    messagingSenderId: '578618171508',
    projectId: 'chat-app-84de6',
    storageBucket: 'chat-app-84de6.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYauOq9JpveEqggILyQW_izKeNJVJqqF4',
    appId: '1:578618171508:web:896b716a0d035751ebf121',
    messagingSenderId: '578618171508',
    projectId: 'chat-app-84de6',
    authDomain: 'chat-app-84de6.firebaseapp.com',
    storageBucket: 'chat-app-84de6.firebasestorage.app',
    measurementId: 'G-KN61P6KM7C',
  );

}